version: 3
env:
  CGO_ENABLED: 0
  GOOS: "linux"
  GOARCH: "amd64"
  GOPROXY: https://proxy.golang.org,direct

vars:
  LD_FLAGS: "-s -w"

includes:
  golang: tasks/golang.yml
  client: example/client/tasks.yml
  server: example/server/tasks.yml
  tls-cert: shared/tls-cert/tasks.yml

tasks:
  format:
    desc: format code
    cmds:
      - gofumpt -l -w ./
  lint:
      desc: golangcli lint
      cmds:
        - golangci-lint run .

  default:
    cmds:
      - task -l
    silent: true
