package transport

import "errors"

var (
	ErrClosed                  = errors.New("transport: engine or transport is closed")
	ErrWouldBlock              = errors.New("transport: send queue is full")
	ErrFrameExceedsQueueBudget = errors.New("transport: encoded frame exceeds queued-byte budget")
	ErrNilContext              = errors.New("transport: nil context")
	ErrNilFramer               = errors.New("transport: framer factory returned nil")
	ErrNilCipherFactory        = errors.New("transport: cipher factory is nil")
	ErrNilCipher               = errors.New("transport: cipher factory returned nil")
	ErrConflictingCodecOptions = errors.New("transport: custom stream framer and message cipher cannot be combined")
	ErrFramerNotSupported      = errors.New("transport: custom stream framer is not supported by this protocol")
	ErrInvalidFramer           = errors.New("transport: framer returned an invalid consumed length")
	ErrReadBufferFull          = errors.New("transport: buffered unread data exceeded the configured limit")
	ErrMessageTooLarge         = errors.New("transport: application message exceeds configured limit")
	ErrDatagramTooLarge        = errors.New("transport: UDP datagram exceeds configured limit")
	ErrInvalidQueueSize        = errors.New("transport: write queue size must be positive")
	ErrInvalidBuffer           = errors.New("transport: buffer sizes must be positive")
	ErrInvalidQueuedBytes      = errors.New("transport: queued-byte limit must be positive")
	ErrInvalidMessageSize      = errors.New("transport: message size limit must be positive")
	ErrInvalidDatagramSize     = errors.New("transport: datagram size limit must be between 1 and 65507 bytes")
	ErrProtocolMismatch        = errors.New("transport: endpoint protocol does not match operation")
	ErrNotConnected            = errors.New("transport: UDP socket is not connected")
	ErrPeerRequired            = errors.New("transport: UDP peer address is required")
	ErrPeerMismatch            = errors.New("transport: UDP peer does not match connected remote")
	ErrTLSConfigRequired       = errors.New("transport: server TLS configuration is required")
	ErrTLSVersion              = errors.New("transport: TLS 1.3 or newer is required")
	ErrTLSCertificateRequired  = errors.New("transport: server TLS certificate is required")
	ErrInvalidTimeout          = errors.New("transport: timeout must be positive")
	ErrInvalidWebSocketConfig  = errors.New("transport: invalid WebSocket configuration")
)
